name: Testing Configuration Variables

on: 
  workflow_dispatch

env:
  cloud: google_cloud


jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Configuration variable test"
        run: echo "$Greeting $First_Name is using $cloud with project: ${{vars.PROJECT_ID }}"
        env:
          First_Name: Sanjeet
