name: Variable Demo
on: push

env:
  GLOBAL_VAR: "I am everywhere" # Available to all jobs

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "I am only in this job"
    steps:
      - name: Print variables
        run: |
          echo "Global: $GLOBAL_VAR"
          echo "Job: $JOB_VAR"
          echo "Step: $First_Name"
        env:
          First_Name: "Sanjeet Kumar"
